version: 2.1
orbs:
  slack: circleci/slack@4.0
jobs: 
  test:    
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "test my app"
      - slack/notify:
          event: fail
          template: basic_fail_1
          #mentions: "@EngineeringTeam"
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

  build:    
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "build my app"
      - slack/notify:
          event: fail
          template: basic_fail_1
          #mentions: "@EngineeringTeam"
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1